Train 1/10  0 loss:0.277
Train 1/10  100 loss:0.265
Train 1/10  200 loss:0.213
Train 1/10  300 loss:0.186
Train 1/10  400 loss:0.170
Train 1/10  500 loss:0.172
Train 1/10  600 loss:0.144
Test 1/10  0 loss:0.136
Test 1/10  10 loss:0.157
Test 1/10  20 loss:0.123
Test 1/10  30 loss:0.114
Test 1/10  40 loss:0.151
Test 1/10  50 loss:0.161
Test 1/10  60 loss:0.134
Test 1/10  70 loss:0.143
Test 1/10  80 loss:0.140
Test 1/10  90 loss:0.124
Test 1/10  100 loss:0.169
Test 1/10  110 loss:0.123
Test 1/10  120 loss:0.130
Test 1/10  130 loss:0.150
Test 1/10  140 loss:0.121
Test 1/10  150 loss:0.142
Test 1/10  160 loss:0.121
Test 1/10  170 loss:0.122
Test 1/10  180 loss:0.156
Test 1/10  190 loss:0.137
Test 1/10  200 loss:0.117
Test 1/10  210 loss:0.162
Test 1/10  220 loss:0.153
Test 1/10  230 loss:0.135
Test 1/10  240 loss:0.163
Test 1/10  250 loss:0.156
Test 1/10  260 loss:0.125
Test 1/10  270 loss:0.144
Test 1/10  280 loss:0.132
Test 1/10  290 loss:0.121
Test 1/10  300 loss:0.135
Test 1/10  310 loss:0.135
Test 1/10  320 loss:0.128
Test 1/10  330 loss:0.181
Test 1/10  340 loss:0.171
Test 1/10  350 loss:0.172
Test 1/10  360 loss:0.160
Test 1/10  370 loss:0.185
Test 1/10  380 loss:0.229
Test 1/10  390 loss:0.143
Test 1/10  400 loss:0.175
Test 1/10  410 loss:0.088
Test 1/10  420 loss:0.137
Test 1/10  430 loss:0.175
Test 1/10  440 loss:0.126
Test 1/10  450 loss:0.123
Test 1/10  460 loss:0.174
Test 1/10  470 loss:0.119
Test 1/10  480 loss:0.141
Test 1/10  490 loss:0.226
Test 1/10  500 loss:0.192
Test 1/10  510 loss:0.130
Test 1/10  520 loss:0.140
Test 1/10  530 loss:0.211
Test 1/10  540 loss:0.114
Test 1/10  550 loss:0.133
Test 1/10  560 loss:0.145
Test 1/10  570 loss:0.196
Test 1/10  580 loss:0.105
Test 1/10  590 loss:0.151
Test 1/10  600 loss:0.131
Test 1/10  610 loss:0.098
Test 1/10  620 loss:0.112
Traceback (most recent call last):
  File "/Users/dongtianchi/Documents/GIT/Magnetic/EXE/AE/ae.py", line 168, in <module>
    wandb.save(net, f'./output/ae/models/m_{epoch}.pkl')
  File "/opt/anaconda3/envs/ForEXE/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/anaconda3/envs/ForEXE/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1744, in save
    return self._save(glob_str, base_path, policy)
  File "/opt/anaconda3/envs/ForEXE/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1760, in _save
    raise ValueError("Must call wandb.save(glob_str) with glob_str a str")
ValueError: Must call wandb.save(glob_str) with glob_str a str